export const navLinks = [
  { id: 'about', title: 'About' },
  { id: 'skills', title: 'Skills' },
  { id: 'experience', title: 'Experience' },
  { id: 'projects', title: 'Projects' },
  { id: 'certifications', title: 'Certifications' },
  { id: 'contact', title: 'Contact' },
]

export const skills = [
  { name: 'JavaScript', abbr: 'JS', color: '#F7DF1E' },
  { name: 'TypeScript', abbr: 'TS', color: '#3178C6' },
  { name: 'React', abbr: 'Re', color: '#61DAFB' },
  { name: 'Next.js', abbr: 'Nx', color: '#ffffff' },
  { name: 'Node.js', abbr: 'No', color: '#339933' },
  { name: 'Express', abbr: 'Ex', color: '#aaa6c3' },
  { name: 'MongoDB', abbr: 'Mg', color: '#47A248' },
  { name: 'PostgreSQL', abbr: 'Pg', color: '#336791' },
  { name: 'Docker', abbr: 'Dk', color: '#2496ED' },
  { name: 'Java', abbr: 'Ja', color: '#ED8B00' },
  { name: 'Python', abbr: 'Py', color: '#3776AB' },
  { name: 'WebRTC', abbr: 'WR', color: '#00cea8' },
  { name: 'Socket.IO', abbr: 'So', color: '#915EFF' },
  { name: 'Tailwind', abbr: 'Tw', color: '#06B6D4' },
  { name: 'Git', abbr: 'Gi', color: '#F05032' },
  { name: 'C++', abbr: 'C+', color: '#00599C' },
]

export const experiences = [
  {
    title: 'Micro1 — Backend JSON Schema Developer',
    company: 'Micro1 Inc.',
    date: 'January 2026',
    desc: 'Passed international technical interview. Certified as a Backend JSON Schema Developer by Micro1, a global AI hiring company.',
    color: '#00cea8',
  },
  {
    title: 'Oracle Data Platform Foundations Associate',
    company: 'Oracle Corporation',
    date: 'January 2026',
    desc: 'Earned the Oracle Data Platform 2025 Certified Foundations Associate credential, validating expertise in Oracle cloud data platform fundamentals.',
    color: '#F80000',
  },
  {
    title: 'Cloud Computing — Elite Performer',
    company: 'NPTEL · IIT Kharagpur',
    date: 'October 2025',
    desc: 'Achieved Elite certification with a 71% score in Cloud Computing from IIT Kharagpur. Recognized as a top performer in the cohort.',
    color: '#915EFF',
  },
  {
    title: 'Foundations and Data Structures',
    company: 'CodeSmart',
    date: 'July 2025',
    desc: 'Completed intensive training in Data Structures using C, C++, and Java. Built real-world applications with React and Tailwind, implementing a custom min-heap for priority-based alert management.',
    color: '#bf61ff',
  },
  {
    title: 'Code-A-Hunt Hackathon — Finalist',
    company: 'Coding Blocks · LPU',
    date: 'February 2024',
    desc: 'Competed against inter-university engineering teams. Advanced safely to the semifinals in this competitive hackathon.',
    color: '#00cea8',
  },
]

export const projects = [
  {
    name: 'SyncSpace',
    desc: 'Real-time collaboration platform architected for 10,000+ concurrent users. Features WebRTC mesh calling, Redis Pub/Sub for distributed events, and MongoDB Atlas Replica Set with compound indexing.',
    tags: ['React 18', 'TypeScript', 'WebRTC', 'Socket.IO', 'MongoDB', 'Redis', 'JWT', 'OAuth'],
    github: 'https://github.com/SantoshMalana/syncspace-chat-app',
    live: 'https://syncspace-realtime-collaboration-pl.vercel.app',
    color: '#915EFF',
    featured: true,
    image: '/syncspace-banner.png',
  },
  {
    name: 'Rideshare Hub',
    desc: 'Full-stack carpooling platform using Next.js 15 App Router and Server Actions — eliminating REST APIs entirely. OTP-based login, Pusher real-time comms, Leaflet maps, and npm monorepo architecture.',
    tags: ['Next.js 15', 'TypeScript', 'MongoDB', 'Pusher', 'Leaflet', 'Framer Motion', 'Tailwind'],
    github: 'https://github.com/SantoshMalana/rideshare-connect-main',
    live: 'https://rideshare-connect-main.vercel.app/',
    color: '#00cea8',
    featured: true,
    image: '/rideshare-banner.png',
  },
  {
    name: 'Loan Management System',
    desc: 'End-to-end financial platform modeling the full loan lifecycle — pending, sanctioned, disbursed, rejected, returned states. Role-based permissions between applicants and branch managers with 24-hour JWT sessions.',
    tags: ['React', 'Node.js', 'Express.js', 'MongoDB', 'JWT', 'Bcrypt', 'Nodemailer'],
    github: 'https://github.com/SantoshMalana/loan-management-system',
    live: 'https://loan-management-system-kappa-eight.vercel.app/',
    color: '#bf61ff',
    featured: true,
    image: '/loan-management-banner.png',
  },
  {
    name: 'Haleem — Perfume Store',
    desc: 'Client-commissioned e-commerce storefront for a luxury perfume brand. Designed with a premium aesthetic, smooth product browsing, and a fully responsive layout built for real-world business use.',
    tags: ['React', 'TypeScript', 'Tailwind', 'Framer Motion'],
    github: 'https://github.com/SantoshMalana/Perfume-client',
    live: 'https://haleem-ten.vercel.app/',
    color: '#F7DF1E',
    featured: true,
    image: '/haleem-banner.png',
  },
  {
    name: 'Real-Time Process Monitor',
    desc: 'Graphical dashboard displaying live process states, CPU usage, and memory consumption. Enables admins to inspect and manage system processes efficiently from one interface.',
    tags: ['JavaScript', 'Node.js', 'Dashboard', 'Real-Time', 'Charts'],
    github: 'https://github.com/SantoshMalana/Real-Time-Process-Monitoring-Dashboard',
    live: '',
    color: '#00cea8',
    featured: false,
    image: '/process_monitor_banner.png',
  },
  {
    name: 'Donate Blood Save Lives',
    desc: 'Blood donation platform connecting donors with hospitals and patients in need. Built with TypeScript for type-safe data handling across the donor registration and request flow.',
    tags: ['TypeScript', 'React', 'Node.js', 'MongoDB', 'Healthcare'],
    github: 'https://github.com/SantoshMalana/donate-blood-save-lives',
    live: '',
    color: '#F80000',
    featured: false,
    image: '/blood_donate_banner.png',
  },
  {
    name: 'Weather Alert Scheduler',
    desc: 'Smart scheduling tool that creates and manages weather-triggered alerts. Users define conditions and thresholds — when matched, the system fires the configured notification.',
    tags: ['HTML', 'CSS', 'JavaScript', 'Weather API', 'Scheduling'],
    github: 'https://github.com/SantoshMalana/Weather-alert-scheduler-',
    live: '',
    color: '#3178C6',
    featured: false,
    image: '/weather_alert_banner.png',
  },
  {
    name: 'Simon Game',
    desc: 'Classic memory-based Simon game with progressive difficulty. Built entirely in vanilla JavaScript — tests pattern retention with colour and sound sequences that grow with each round.',
    tags: ['JavaScript', 'HTML', 'CSS', 'Game', 'DOM'],
    github: 'https://github.com/SantoshMalana/simon-game',
    live: '',
    color: '#F7DF1E',
    featured: false,
    image: '/simon-game-banner.png',
  },
  {
    name: 'Portfolio Website',
    desc: 'This very portfolio — built with React 18, Spline 3D, Framer Motion, and Tailwind CSS. Features interactive 3D boxes hero, animated role cycling, scroll spy, and smooth scroll animations.',
    tags: ['React 18', 'TypeScript', 'Spline', 'Framer Motion', 'Tailwind'],
    github: 'https://github.com/SantoshMalana',
    live: '',
    color: '#915EFF',
    featured: false,
    image: '/portfolio_banner.png',
  },
]

export const certifications = [
  {
    title: 'Oracle Data Platform Foundations',
    issuer: 'Oracle Corporation',
    date: 'Jan 2026',
    abbr: 'OR',
    color: '#F80000',
    bg: 'rgba(248,0,0,0.08)',
    link: 'https://drive.google.com/file/d/1k1AxNALgZRZGdZ1s8ATgy4F7Ahj0LDtx/view?usp=drive_link',
  },
  {
    title: 'Oracle Cloud Infrastructure 2025 AI Foundations Associate',
    issuer: 'Oracle Corporation',
    date: '2025',
    abbr: 'AI',
    color: '#F80000',
    bg: 'rgba(248,0,0,0.08)',
    link: 'https://drive.google.com/file/d/1fqE_JuOaGumVZvUNwzAi13jisP4wTlGM/view?usp=drive_link',
  },
  {
    title: 'Backend JSON Schema Developer',
    issuer: 'Micro1 Inc.',
    date: 'Jan 2026',
    abbr: 'M1',
    color: '#00cea8',
    bg: 'rgba(0,206,168,0.08)',
    link: 'https://drive.google.com/file/d/13DEpFJFljHOk5iRHOcVboMexcc9V1WbM/view?usp=sharing',
  },
  {
    title: 'Cloud Computing — Elite',
    issuer: 'NPTEL · IIT Kharagpur',
    date: 'Oct 2025',
    abbr: 'NP',
    color: '#915EFF',
    bg: 'rgba(145,94,255,0.08)',
    link: 'https://drive.google.com/file/d/1pf5va761HL972cgI6onGbreBaz8dFb69/view?usp=drive_link',
  },
  {
    title: 'Code-A-Hunt Hackathon',
    issuer: 'Coding Blocks · LPU',
    date: 'Feb 2024',
    abbr: 'CB',
    color: '#bf61ff',
    bg: 'rgba(191,97,255,0.08)',
    link: 'https://drive.google.com/file/d/1YVy5zrmL8SpZgwSrXq_GdO_olpCX-04w/view?usp=sharing',
  },
]
